# Generated by Django 2.2.1 on 2019-06-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_remove_skillsets_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_link', models.URLField()),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField()),
            ],
        ),
    ]
