# Generated by Django 2.2.1 on 2019-06-13 14:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_image',
            field=cloudinary.models.CloudinaryField(default='null', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
